#
#                                      █▄░█ █▀█ ▀█▀ █▀▀
#                                      █░▀█ █▄█ ░█░ ██▄
#
#   -----------------------| CI WORKFLOW   |   main => beta => prod |-----------------------
#
#     - don't use "script:" unless you want to override the template
#       use before or after script instead
#     - tell the author before make some changes (customizing can break the workflow and ..
#       make the author have an headache)
#     - if you want to create a new branch describe the branch with name that descibe the 
#       perpouse of it
#   ----------------------------------------------------------------------------------------

include:
  - project: 'rumahlogic/public-ci-templates'
    ref: main
    file: 'template.yml'

deliver:
  rules:
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "beta"
      when: always
    - when: never
  variables:
    DEV_SERVER: "siacc-dev"
    BETA_SERVER: "cp-siacc-beta"
    DEV_TARGET_NAME: "siaccred_ui"
    DEV_ORCESTRATORS: "docker-compose"
    BETA_SERVER: "siacc-beta"
    BETA_TARGET_NAME: "siaccred_ui"
    BETA_ORCESTRATORS: "docker-compose"
  when: on_success

push-to-prod:
  rules:
    - if: $CI_COMMIT_BRANCH == "prod"
      when: always
    - when: never
  variables:
    WORKDIR: "SIACC"
    DEVELOPMENT_URL: "git@gitlab.com:microservice-repos/siacc/"
    DEVELOPMENT_REPO: "frontend-siacc"
    PRODUCTION_URL: "git@gitlab.com-prod:a3infiniti-microservices/"
    PRODUCTION_REPO: "5a1d82cc6821588af2f0fa110bf71946"
    BRANCH: "prod"
    TARGET_BRANCH: "main"