#
#                                      █▄░█ █▀█ ▀█▀ █▀▀
#                                      █░▀█ █▄█ ░█░ ██▄
#
#   -----------------------| CI WORKFLOW   |   main => beta => prod |-----------------------
#
#     - don't use "script:" unless you want to override the template
#       use before or after script instead
#     - tell the author before make some changes (customizing can break the workflow and ..
#       make the author have an headache)
#     - if you want to create a new branch describe the branch with name that descibe the 
#       perpouse of it
#   ----------------------------------------------------------------------------------------

include:
  - project: 'microservice-repos/ci-template'
    ref: main
    file: '/template-siacc2.yml'

deliver:
  variables:
    DEV_TARGET_NAME: "siaccred_ui"
    ORCESTRATORS_DEV: "docker-compose"
    DEV_TARGET_NAME: "siaccred_ui"
    ORCESTRATORS_BETA: "docker-compose"

push-to-prod:
  variables:
    WORKDIR: "SIACC"
    RLI_REPO: "frontend-siacc"
    PROD_REPO: "5a1d82cc6821588af2f0fa110bf71946"
    BRANCH: "prod"
    TARGET_BRANCH: "main"
