export const feedsURL = {
    gisPrefix                   : "gis",
    feedsPrefix                 : "feeds",
    ratingPrefix                : "rating",
    hashtagPrefix               : "hashtag",
    autoSavePrefix              : "auto-save",
    automationPrefix            : "automation",
    achievementPrefix           : "achievement",
    performancePrefix           : "performance",
    agentPointsPrefix           : "agent-points",
    
    feedsLike                   : "like",
    feedsType                   : "type",
    feedsCount                  : "count",
    feedsViewer                 : "viewer",
    feedsReport                 : "report",
    feedsTrophy                 : "trophy",
    feedsComment                : "comment",
    feedsCategory               : "category",
    feedsReviewed               : "reviewed",
    feedsByParent               : "by-parent",
    feedsByStored               : "by-stored",
    feedsGetByKind              : "by-kind",
    feedsByArchieve             : "by-archive",
    feedsByPosition             : "by-position",
    feedsByWorkunit             : "by-workunit",
    feedsByDateRange            : "by-daterange",
    feedsAgentReport            : "agent-report",
    feedsShareByKind            : "select-kind",
    feedsDeleteByUser           : "delete-by-user",
    feedsByTypeShared           : "by-type-shared",
    feedsByAgentReport          : "by-agent-report",
    feedsUserLikeCheck          : "user-like-check",
    feedsGetByEmployee          : "by-employee",
    feedsGetByCategory          : "by-category",
    feedsGetBySelected          : "change-to-selected",
    feedsGetAttachment          : "attachment/by-agent-report",
    feedsTrendingByType         : "trending-by-type",
    feedsChangeToStored         : "change-to-stored",
    feedsShareByWorkunit        : "share-by-workunit",
    feedsChangeToArchive        : "change-to-archive",
    feedsShareByPosition        : "share-by-position",
    feedsGetCategoryById        : "get-category",
    feedsChangeToSelected       : "change-to-selected",
    feedsSelectReportKind       : "select-kind",
    feedsUploadAttachment       : "upload-attachment",
    feedsDeleteAttachment       : "delete-attachment",
    feedsByPositionShared       : "by-position-shared",
    feedsDeleteFromStored       : "delete-from-stored",
    feedsAgentReportByRole      : "by-login-role",
    feedsCancelFromSelected     : "cancel-from-selected",
    feedsTrendingByCategory     : "trending-by-category",
    feedsAgentReportByStatus    : "by-status",
    feedsInteractionByCategory  : "interaction-by-category",

    //Achievement
    achievementKind             : "kind",
    achievementAgent            : "agent",
    achievementWorkunit         : "workunit",
    achievementUploadBadge      : "upload-badge",
    achievementUpdateBadge      : "update-badge",
    achievementWorkunitSelf     : "self",
    achievementAgentByActive    : "by-active",
    
    pointsDeduction             : "points-deduction",
    
    //Automation
    automationStatement         : "statement",
    automationOperator          : "operator",
    automationValue             : "value",
    automationThen              : "then",
    automationResult            : "result",
    automationGet               : "get",

    get                         : "get",
    all                         : "all",
    map                         : "maps",
    list                        : "list",
    save                        : "save",
    chart                       : "chart",
    draft                       : "draft",
    local                       : "lokal",
    filter                      : "filter",
    create                      : "create",
    update                      : "update",
    detail                      : "detail",
    byKind                      : "by-kind",
    delete                      : "delete",
    byType                      : "by-type",
    byActive                    : "by-active",
    profile                     : "profile",
    isActive                    : "is-active",
};